[project]
name = "villanua-web"
version = "0.1.0"
description = ""
authors = [{name = "Villanua", email = "NachoViCu16@gmail.com"}]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "django>=5.2.4,<6.0",
    "python-dotenv>=1.1.1,<2.0",
    "django-environ>=0.12.0,<1.0",
    "whitenoise>=6.9.0,<7.0",
    "gunicorn>=23.0.0,<24.0",
    "djangorestframework>=3.16.0,<4.0",
    "langchain-google-vertexai>=2.0.27,<3.0",
    "google-cloud-secret-manager>=2.24.0,<3.0",
    "langgraph>=0.5.4,<1.0",
    "langchain-tavily>=0.2.10,<1.0",
    "psycopg2-binary>=2.9.10,<3.0",
    "channels>=4.2.2,<5.0",
    "uvicorn>=0.35.0,<1.0",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
